<?php // @codingStandardsIgnoreFile ?>
<?php
/**
 * Copyright © 2019 Wyomind. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<div id="task-view" style="display: none;" class="messages">
    <span id="error" class="error"></span>
    <table>
        <tr id="tr-task-schedule_id"><td><label><?= /* @noEscape */ __('Task #'); ?></label></td><td><span id="task-schedule_id"></span></td></tr>
        <tr id="tr-task-job_code"><td><label><?= /* @noEscape */ __('Job code'); ?></label></td><td><span id="task-job_code"></span></td></tr>
        <tr id="tr-task-status"><td><label><?= /* @noEscape */ __('Status'); ?></label></td><td><span id="task-status"></span></td></tr>
        <tr id="tr-task-created_at"><td><label><?= /* @noEscape */ __('Created at'); ?></label></td><td><span id="task-created_at"></span></td></tr>
        <tr id="tr-task-scheduled_at"><td><label><?= /* @noEscape */ __('Scheduled at'); ?></label></td><td><span id="task-scheduled_at"></span></td></tr>
        <tr id="tr-task-executed_at"><td><label><?= /* @noEscape */ __('Executed at'); ?></label></td><td><span id="task-executed_at"></span></td></tr>
        <tr id="tr-task-finished_at"><td><label><?= /* @noEscape */ __('Finished at'); ?></label></td><td><span id="task-finished_at"></span></td></tr>
        <tr id="tr-task-origin"><td><label><?= /* @noEscape */ __('Origin'); ?></label></td><td><span id="task-origin"></span></td></tr>
        <tr id="tr-task-user"><td><label><?= /* @noEscape */ __('User'); ?></label></td><td><span id="task-user"></span></td></tr>
        <tr id="tr-task-ip"><td><label><?= /* @noEscape */ __('IP'); ?></label></td><td><span id="task-ip"></span></td></tr>
        <tr id="tr-task-error_file"><td><label><?= /* @noEscape */ __('Error file'); ?></label></td><td><span id="task-error_file"></span></td></tr>
        <tr id="tr-task-error_line"><td><label><?= /* @noEscape */ __('Error line'); ?></label></td><td><span id="task-error_line"></span></td></tr>
        <tr id="tr-task-messages"><td><label><?= /* @noEscape */ __('Messages'); ?></label></td><td><span id="task-messages"></span></td></tr>
    </table>
</div>
